apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: color-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mostafagheta/argoCD_test
    targetRevision: HEAD
    path: solar_sys
  destination:
    server: https://kubernetes.default.svc
    namespace: solar
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true