apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mysql-password
spec:
  encryptedData:
    password: AgAzpeLcO6za4dtYc14cWAlz5et07jZJLEUtGTM9x/NaLreoml/0wFvQs325flmFaVFxxm4UDlrPPh5kg6k/Xk2xsCVVP6mjb4/yPpnrZdDRG1cXzTJp9NB50z4CcTkJ5GMosOoBdzoD48dUiU3Zx0ZxwHl3D4FHOiHdEBNfT5BeDSfU8gMmYUiURo2Srl44ahEuTnWS7G5yUr3r3u5/KZo1qRKMOuA8eK79wcc3Vwy2zUtDkcZQSs/ZIFTaY48CY40/v3mmrAAq5PoFG+6fWJKgI9+VMkYnYk8n0lnmXJeUIFnQPFhvuFjhFsft7CYqYFWhaBU2ps5NR+QbWPz2KQW3q8DLG9Jz/X8Zk54j4kE+Hyza71t0Q2nN3JBN+J++/U0x1dnOTMxOeDAt7TSgq4VZQY92ZxBTVD4vJ9KGHRpnBuZ1egskzOT6MobAPHhXuRnYbjiorfMm24J1cXCx4KshPJETEw/op9Ecp/AIier/S2KI4eb0Ie+cwXd5L4AU89eSecXupPF/kjeqzr+DmuZrc0vgFkcmhZsQ35j2ez0x9huABW681mHgJ7Ln8JJA7G8RlgKKuioHH8JvFa1mae1JCa2I3woBEVE6f1RPnVqPyUC/hjlh6qPt2V9WsOzgDtzhbLOkOHsbmwGscKvg2qEfAJtvhCuiDUF/beg5+EET+9BY4s2I8nLok5x5ZOAKyLWj/VtK58zyeUU=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mysql-password

